portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from app.views import home, register_view
from app.views import projetos, projetos_form, projetos_criar, projetos_editar, projetos_atualizar, projetos_deletar
from app.views import atividades, atividades_form, atividades_criar, atividades_editar, atividades_atualizar, atividades_deletar

from app.views import ProjetosListCreateView, ProjetosDetailView




urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('',home, name='home'),
    path('admin/', admin.site.urls),

    path('projetos/', projetos, name='projetos'),
    path('projetosform/',projetos_form, name='projetosform'),
    path('projetoscriar/', projetos_criar, name='projetoscriar'),
    path('projetoseditar/<int:pk>/', projetos_editar, name='projetoseditar'),
    path('projetosatualizar/<int:pk>/', projetos_atualizar, name='projetosatualizar'),
    path('projetosdeletar/<int:pk>/', projetos_deletar, name='projetosdeletar'),

    path('atividades/', atividades, name='atividades'),

    path('atividadesform/',atividades_form, name='atividadesform'),
    path('atividadescriar/', atividades_criar, name='atividadescriar'),
    path('atividadeseditar/<int:pk>/', atividades_editar, name='atividadeseditar'),
    path('atividadesatualizar/<int:pk>/', atividades_atualizar, name='atividadesatualizar'),
    path('atividadesdeletar/<int:pk>/', atividades_deletar, name='atividadesdeletar'),

    path('api/',include('app.api_urls')),
]

app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile
from .models import Projetos, Atividades

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30, required=True)
    phone_number = forms.CharField(max_length=20)
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2','phone_number']
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        profile = UserProfile(user=user,phone_number=self.cleaned_data['phone_number'])
        profile.save()
        return user
    
class ProjetoForm(ModelForm):
    data_inicio = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}, format='%Y-%m-%d'),
    )
    data_fim = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}, format='%Y-%m-%d'),
    )
    class Meta:
        model = Projetos
        fields = ['nome','descricao','prioridade','data_inicio','data_fim']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'prioridade': forms.Select(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
        }


class AtividadeForm(ModelForm):
    status_atividade = forms.ChoiceField(choices=Atividades.STATUS, label='Status', widget=forms.Select(attrs={'class': 'form-control'})) # Para campo select
    class Meta:
        model = Atividades
        fields = ['nome','projeto','user','status_atividade','prioridade','descricao']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'projeto': forms.Select(attrs={'class': 'form-control'}),
            'user': forms.Select(attrs={'class': 'form-control'}),
            'prioridade': forms.Select(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
        }

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>  
    <script src="https://code.jquery.com/jquery-3.7.1.js" crossorigin="anonymous"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script> 
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js" crossorigin="anonymous"></script> 
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js" crossorigin="anonymous"></script> 
    <link href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> 
    <title>{% block title %}{% endblock %}</title>
     <style>
        body{
            background-color: #eeeeee;
        }
        .navbar-inverse {
            border-radius: 0;
          }
          .margin_user{
            margin-top:7px;
          }
     </style>
</head>
<body>
    {% if user.is_authenticated %}
    <body>
        
    <div class="container">
        
        <div class="col-xl-12">
            
            
                <nav class="navbar navbar-expand-lg bg-light">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#">PosDFS</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link"  href="/">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/projetos/">projetos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/atividades/">Atividades</a>
                                </li>
                                <li class="nav-item">
                                    <form action="{% url 'logout' %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="nav-link btn">Sair</button>
                                    </form>    
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="col-md-12 text-end margin_user">
                    Usuário: {{user.get_username}} 
                </div>
        </div>
    </div>
</body>
    
    {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block content %}
    <div class="col-md-12 m-auto pt-4 pb-2 text-center">
        Bem-vindo!
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<style>
  .gradient-custom-2 {
    /* fallback for old browsers */
    background: #fccb90;
    
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #085b5a, #005f6e, #006289, #0063a8);
    
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #085b5a, #005f6e, #006289, #0063a8);
    }
    
    @media (min-width: 768px) {
    .gradient-form {
    height: 100vh !important;
    }
    }
    @media (min-width: 769px) {
    .gradient-custom-2 {
    border-top-right-radius: .3rem;
    border-bottom-right-radius: .3rem;
    }
    }
</style>
<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
               
                  <h4 class="mt-1 mb-5 pb-1">Login</h4>
                  {% if message %}
                      <p>{{ message }}</p>
                    {% endif %}
                </div>

                <form method="post">
                  {% csrf_token %}
                  <p>Por favor acesse sua conta</p>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="text"  class="form-control" name="username" id="username"
                      placeholder="Login" required/>
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Senha" required/>                    
                  </div>
                  <div class="d-flex   pb-4">
                    <button class='btn btn-success mx-4'type="submit">Logar</button>
                  </div>

                  <div class="d-flex align-items-center justify-content-center pb-4">
                    <p class="mb-0 me-2">Não tem conta?</p>
                    <a href="{% url 'register' %}"  type="button" data-mdb-button-init data-mdb-ripple-color="primary" class="btn btn-outline-primary">Registre-se</a>
                  </div>

                </form>

              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">PosDFS Python</h4>
                <p class="small mb-0">Nosso sistema de agendamento facilita a organização de compromissos, permitindo que você marque, gerencie e visualize suas reuniões de maneira eficiente. Com notificações automáticas, integração com calendários e uma interface intuitiva, seu dia a dia se torna mais produtivo. Ideal para empresas e profissionais que valorizam o tempo e a eficiência. Simplifique sua agenda com nosso sistema.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block content %}
<style>
  .gradient-custom-2 {
    /* fallback for old browsers */
    background: #fccb90;
    
    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(to right, #085b5a, #005f6e, #006289, #0063a8);
    
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, #085b5a, #005f6e, #006289, #0063a8);
    }
    
    @media (min-width: 768px) {
    .gradient-form {
    height: 100% !important;
    }
    }
    @media (min-width: 769px) {
    .gradient-custom-2 {
    border-top-right-radius: .3rem;
    border-bottom-right-radius: .3rem;
    }
    }
</style>
<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
               
                  <h4 class="mt-1 mb-5 pb-1">Registrar Usuário</h4>
                  {% if message %}
                      <p>{{ message }}</p>
                    {% endif %}
                </div>

                <form method="post">
                  {% csrf_token %}
                  <p>Por favor informe os dados abaixo:</p>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_first_name">Nome:</label>
                    <input type="text" name="first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% else %}{{ '' }}{% endif %}"  class="form-control" maxlength="150" autofocus="" required id="first_name" >
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_last_name">Sobrenome:</label>
                    <input type="text" name="last_name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus="" required id="last_name">
                  </div>
                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_email">E-mail:</label>
                    <input type="email" name="email" value="{% if form.email.value %}{{ form.email.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus=""  id="email" placeholder="exemplo@mail.com" required>
                  </div>
                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_phone_number">Telefone:</label>
                    <input type="text" name="phone_number" value="{% if form.phone_numbe.value %}{{ form.phone_numbe.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus=""  id="phone_numbe"  >
                  </div>
                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_username">Usuário:</label>
                    <input type="text" name="username" value="{% if form.username.value %}{{ form.username.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus="" required="" id="id_username">
                  </div>
                  
                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_password1">Senha:</label>
                    <input type="password" name="password1" value="{% if form.password1.value %}{{ form.password1.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus="" required="" id="password1">
                  </div>
                  <div data-mdb-input-init class="form-outline mb-4">
                    <label for="id_password2">Repita a Senha:</label>
                    <input type="password" name="password2" value="{% if form.password2.value %}{{ form.password2.value }}{% else %}{{ '' }}{% endif %}" class="form-control" maxlength="150" autofocus="" required="" id="password2">
                  </div>

                  <div class="d-flex align-items-center justify-content-center pb-4">
                    {% if form.errors %}
              <div class="col-md-12 alert alert-danger  mt-4">
                {% for field, errors in form.errors.items %}
                  {% for error in errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                {% endfor %}
              </div>
            {% endif %}
                    
                  </div>
                  <button  class='btn btn-success mt-4'  type="submit">Registrar</button>

                </form>

              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">Segurança:</h4>
                <p class="small mb-0">Para garantir a segurança digital, mantenha seus softwares atualizados, pois atualizações frequentes corrigem vulnerabilidades. Utilize senhas fortes e únicas para cada conta e considere um gerenciador de senhas para facilitar. Ative a autenticação de dois fatores (2FA) para uma camada extra de segurança. Nunca compartilhe suas senhas e evite anotá-las em lugares acessíveis. Seja cauteloso ao clicar em links ou abrir anexos de e-mails desconhecidos para evitar phishing. Realize backups regulares dos seus dados para evitar perda em caso de ataque. Mantenha um antivírus atualizado e ativo. Verifique sempre a autenticidade dos sites antes de fornecer informações pessoais. Essas práticas ajudam a proteger sua privacidade e segurança online.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}